
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jamify-uaa
    username: postgres
    password: postgres

  liquibase:
    user: postgres
    password: postgres
  security:
    oauth2:
      client:
          registration:
            spotify:
              redirect-uri: "http://localhost:8081/login/oauth2/code/spotify"
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

logging:
  level:
    com.jamify.uaa: debug
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: trace
    com.jamify.uaa.config.com.jamify.uaa.config.LoggingFilter: DEBUG

gateway:
  url: http://localhost:5173 # test front for now til gateway is implemented
#  url: http://localhost:8083 # test front for now til gateway is implemented
  service:
    front: "" # no need to add /

security:
  jwt:
    # in resources folder
    private-key: classpath:private.pem
    public-key: classpath:public.pem
    jwk-key-id: jamify-uaa-key-id
config:
  jamify-engine:
    url:
     base: http://localhost:8082/api/v1
    api-key: super-secret-dev-key

server:
  servlet:
    session:
      cookie:
        secure: false