# application.yml
spring:
  application:
    name: jamify-uaa

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/spotify"
            # https://developer.spotify.com/documentation/web-api/concepts/scopes
            scope: user-read-email, user-read-private, playlist-read-private, playlist-read-collaborative, playlist-modify-public, playlist-modify-private, user-top-read, user-library-read, user-read-currently-playing
          amazon:
            client-id: ${AMAZON_CLIENT_ID}
            client-secret: ${AMAZON_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/amazon"
            scope: profile # TODO
#          apple:
#            client-id: ${APPLE_CLIENT_ID}
#            client-secret: ${APPLE_CLIENT_SECRET}
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/apple"
#            scope: user-read #TODO
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id
          amazon:
            authorization-uri: https://www.amazon.com/ap/oa
            token-uri: https://api.amazon.com/auth/o2/token
            user-info-uri: https://api.amazon.com/user/profile
            user-name-attribute: user_id
#          apple:
#            authorization-uri: https://appleid.apple.com/auth/oauth2/v2/authorize
#            token-uri: https://appleid.apple.com/auth/oauth2/v2/token
#            user-info-uri: https://api.music.apple.com/v1/me
#            user-name-attribute: sub


      resourceserver:
        jwt:
          # TODO
          issuer-uri: http://localhost:8081


  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  servlet:
    session:
      cookie:
        name: jamify-auth
        secure: true

logging:
  level:
    root: info

gateway:
    url: https://gateway_url_when_implemented
    service:
      front: /mobile-app

security:
  jwt:
    private-key: ${JWT_PRIVATE_KEY}
    public-key: ${JWT_PUBLIC_KEY}
    jwk-key-id: ${JWK_KEY_ID}
    refresh-token:
        expiration: 2592000000 # 30 day in ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true

config:
  jamify-engine:
    url: ${JAMIFY_ENGINE_BASE_URL}
    api-key: ${JAMIFY_ENGINE_API_KEY}
