spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jamify-uaa
    username: postgres
    password: postgres

  liquibase:
    user: postgres
    password: postgres

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    com.jamify.uaa.config.com.jamify.uaa.config.LoggingFilter: DEBUG

gateway:
  url: http://localhost:5173 # test front for now til gateway is implemented
  service:
    front: "" # no need to add /

security:
  api-key:
    jamify-engine: super_secure_key
  jwt:
    private-key: private.pem
    public-key: public.pem
