services:
  postgres-uaa:
    image: postgres:16
    environment:
      POSTGRES_DB: jamify-uaa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 15s
      timeout: 2s
      retries: 15
    ports:
      - "5433:5432"